/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ferofluid (https://sketchfab.com/ferofluid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-lowpoly-asset-ed185bc3004e4770b81d7fab830eb825
Title: MacBook Lowpoly Asset
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { editable as e } from "@theatre/r3f"
import { useMediaQuery } from "@uidotdev/usehooks";

export function MacBookGroup(props) {
    const { nodes, materials } = useGLTF("/macbook_lowpoly_asset.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.218}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP13001_MBP13_0.geometry}
                        material={materials.MBP13}
                        position={[-15.843, 5.109, -26.358]}
                        rotation={[0.639, 1.188, 2.539]}
                        scale={35.221}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP13Screen001_MBP13_0.geometry}
                        material={materials.MBP13}
                        position={[-15.843, 5.109, -26.358]}
                        rotation={[-0.869, 1.106, -2.328]}
                        scale={35.221}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP14001_MBP14_0.geometry}
                        material={materials.MBP14}
                        position={[-5.052, 6.608, 55.276]}
                        rotation={[2.917, 0, 0]}
                        scale={35.558}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP14Screen001_MBP14_0.geometry}
                        material={materials.MBP14}
                        position={[-5.052, 6.541, 55.276]}
                        rotation={[-2.793, 0, 0]}
                        scale={35.558}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP16001_MBP16_0.geometry}
                        material={materials.MBP16}
                        position={[57.013, 6.888, 12.063]}
                        rotation={[0.393, -0.951, -2.816]}
                        scale={40.569}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.MBP16Screen001_MBP16_0.geometry}
                        material={materials.MBP16}
                        position={[57.013, 6.508, 12.063]}
                        rotation={[-0.584, -0.902, 2.663]}
                        scale={40.569}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/macbook_lowpoly_asset.glb");